### ISSUE TITLE
Exception: Action Auth Audit: group_member_delete

### ISSUE THREAD

**Issue by mkuder** [datagovuk/dgu-vagrant-puppet#110]
Hello, 

I have come across a problem trying to add some group member functionality to our install of DGU (I am working with @zvetaM who also reported some issues). Adding members to groups works ok through group_member_create. However, using group_member_delete throws an error: 'Exception: Action Auth Audit: group_member_delete'. I believe this is due to the fact that the ['member_delete' method in delete.py](https://github.com/datagovuk/ckan/blob/release-v2.2-dgu/ckan/logic/action/delete.py#L280) of the 'release-v2.2-dgu' CKAN branch checks access to member_create instead of member_delete. Can you please correct this?

Is this otherwise the right branch of dgu CKAN to be installing for DGU To Go or would you recommend moving to another one in your repository?

EDIT: It seems that [this commit](https://github.com/datagovuk/ckan/commit/f9f39eb71fafbc6fd84cd4d0aea0117c88028188) of the release-v2.4.0-dgu branch might solve these problems.

Best regards,
Marko

**Comment by davidread** [comment]
Yes, this is the branch of ckan we use currently.

I agree that commit/PR looks v likely. Do you want to try it, and if it does, do a PR for our fork/branch and I'll merge it in?

**Comment by mkuder** [comment]
I tried it out and the member creation and deletion works properly now. I submitted a pull request with the necessary changes from the commit.

**Comment by davidread** [comment]
Great, merged
