### ISSUE TITLE
CKAN permissions error

### ISSUE THREAD

**Issue by goozi** [datagovuk/dgu-vagrant-puppet#51]
Follow the readme step by step. Every thing look ok but data menu. 
When i click data menu, the url point to /data/search and show error below:
---------------------------------------------------------------------------------------------------------------
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, [no address given] and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Apache/2.2.22 (Ubuntu) Server at 182.92.192.78 Port 80

**Comment by davidread** [comment]
So the error is when wsgi_app.py tries to execute activate_this.py.

These are the permissions I have for activate_this:
```
(ckan)co@precise64:/src/ckan$ ls -l /home/co/ckan/bin/activate_this.py
-rw-r--r-- 1 co co 1129 Sep 22 16:37 /home/co/ckan/bin/activate_this.py
```
So clearly only global read permission is used for this, and you've got that.

I don't have a system to test this on, but there is a hint here about the directories above it needing the right permissions:
http://stackoverflow.com/questions/22234238/apache2-virtualenv-ioerror-errno-13-permission-denied

so you could compare with what I have:
```
(ckan)co@precise64:/src/ckan$ ls -l /home/co/ckan/ |grep bin
drwxr-xr-x 2 co co   4096 Dec 16 15:03 bin
(ckan)co@precise64:/src/ckan$ ls -l /home/co/ |grep ckan
drwxr-xr-x 10 co co    4096 Jan  2 12:53 ckan
(ckan)co@precise64:/src/ckan$ ls /var -l |grep ckan
drwxrwxr-x  5 www-data www-data 4096 Dec 17 17:39 ckan
(ckan)co@precise64:/src/ckan$ ls / -l |grep var
drwxr-xr-x  13 root     root      4096 Oct  2 10:33 var
```

**Comment by davidread** [comment]
I found that this issue was appearing on Vagrant too, so I tracked down the issue. It was because the permissions of /home/co/ckan didn't allow all to execute it. I think the python puppet module changed its default.

I've added the correct option now: 
https://github.com/datagovuk/dgu-vagrant-puppet/commit/b7e91e73cd21dddd6b122d82d42b6318049ead40#diff-b287f406ee2e072ce80b37bdf7ee23e2R44

or you can fix this on your machine manually like this:
```
(ckan)co@precise64:/src/ckan$ ls /home/co/ -l
total 4
drwxr-x--- 9 co co 4096 Jan 26 17:16 ckan
(ckan)co@precise64:/src/ckan$ chmod a+rx /home/co/ckan
(ckan)co@precise64:/src/ckan$ ls /home/co/ -l
total 4
drwxr-xr-x 9 co co 4096 Jan 26 17:16 ckan
(ckan)co@precise64:/src/ckan$ umask
0002
```
