### ISSUE TITLE
togo branch: nltk install currently fails, needs setuptools==9.1

### ISSUE THREAD

**Issue by CarlQLange** [datagovuk/dgu-vagrant-puppet#56]
The nltk team have an issue that causes install to fail with newer versions of setuptools: https://github.com/nltk/nltk/issues/824

I attempted to add `"setuptools==9.1"` to `$pip_pkgs_remote` but it didn't like that much (didn't work very hard at that though). Got around it by ssh-ing into the machine and manually doing

    sudo su co
    pip install setuptools==9.1
    pip install nltk==2.0.4

and then `vagrant provision` again.

This issue may be fixed by the nltk team, but the version you rely on in the `togo` branch will need to be changed once they fix it. Otherwise a better workaround may be necessary.

**Comment by davidread** [comment]
Cheers Carl, good to know this. Let's wait until they fix it before we fix the puppet.

BTW when adding items to $pip_pkgs_remote one also has to add the package to the repo. We do this because there were lots of problems of packages not being available at all times.

**Comment by CarlQLange** [comment]
:+1:
