### ISSUE TITLE
togo branch: Had to allow apache to access wsgi_app.py and friends

### ISSUE THREAD

**Issue by CarlQLange** [datagovuk/dgu-vagrant-puppet#58]
On the togo branch: Had to do

    sudo su co
    chown -R www-data:www-data ./ckan

to stop apache getting permissions errors trying to execute wsgi_app.py and company. I'm sure there's a better way to do that.

**Comment by davidread** [comment]
Apache just needs read access to /var/ckan/wsgi_app.py (as mentioned in the issue title) so I think that shouldn't be an issue. I think in your command you are refering to /src/ckan/ckan which mod_wsgi will just need read permission to.

Perhaps you could provide more details:
1. whether you are using vagrant or a fresh box
2. full error message you saw
3. before and after ownership and permissions
4. full path to the files you changed

cheers

**Comment by davidread** [comment]
Ah, is this the same as this: https://github.com/datagovuk/dgu-vagrant-puppet/issues/51 ?

**Comment by CarlQLange** [comment]
Just went through this again, here's the exact steps I followed:

![screen shot 2015-01-27 at 11 53 53](https://cloud.githubusercontent.com/assets/859820/5918040/d56ad452-a61b-11e4-99d7-64117c0647f4.png)

and

![screen shot 2015-01-27 at 11 59 19](https://cloud.githubusercontent.com/assets/859820/5918052/fa02e912-a61b-11e4-849e-7ce84075e990.png)

**Comment by davidread** [comment]
I think the fix I did today for #51 would do it?

**Comment by CarlQLange** [comment]
I think you're probably right. I'll have a look to confirm in the next few days but I had a very similar fix (which was broken for unrelated reasons).
I felt that I also had to chown `/var/ckan/wsgi_app.py` but I might well be wrong.

**Comment by CarlQLange** [comment]
Yep, your fix at https://github.com/datagovuk/dgu-vagrant-puppet/commit/5667b6f502f1cd7b62ecacd7dc1f36847f091eaa solved the issue. Thanks a lot!!

**Comment by davidread** [comment]
Great, cheers for helping out with all this @CarlQLange

**Comment by CarlQLange** [comment]
Well, thank you for open-sourcing such useful stuff!
