### ISSUE TITLE
Error trying to install ckan using "Option 2: Fresh machine preparation"

### ISSUE THREAD

**Issue by gianmere** [datagovuk/dgu-vagrant-puppet#59]
Hi,

I have an error when I try to install ckan using a fresh machine.

When I write this command:
"sudo -u www-data paster --plugin=ckanext-harvest harvester gather_consumer --config=../ckan/ckan.ini"

I have this error message:

Traceback (most recent call last):
  File "/usr/bin/paster", line 4, in <module>
    command.run()
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 93, in run
    commands = get_commands()
  File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 135, in get_commands
    plugins = pluginlib.resolve_plugins(plugins)
  File "/usr/lib/python2.7/dist-packages/paste/script/pluginlib.py", line 82, in resolve_plugins
    pkg_resources.require(plugin)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Not Found: ckanext-harvest (did you run python setup.py develop?)

How can I fix it ?

**Comment by davidread** [comment]
It looks like one of these two stages didn't work:

1. when running git_clone_all when you clone ckanext-harvest:

https://github.com/datagovuk/dgu-vagrant-puppet/blob/togo/src/git_clone_all.sh#L43

2. when ckanext-harvest is installed into the vm:

https://github.com/datagovuk/dgu-vagrant-puppet/blob/togo/puppet/modules/dgu_ckan/manifests/init.pp#L149

Can you try again from fresh and provide the log messages from these two moments?

**Comment by davidread** [comment]
Ah wait, no I think you just need to use a path to the correct paster. Try:

sudo -u www-data /home/co/ckan/bin/paster --plugin=ckanext-harvest harvester gather_consumer --config=/var/ckan/ckan.ini

and if it works I'll update the doc.

**Comment by gianmere** [comment]
You're right , I tried:

sudo -u www-data /home/co/ckan/bin/paster --plugin=ckanext-harvest harvester gather_consumer --config=/var/ckan/ckan.ini

and it worked !!!
Thanks a lot

**Comment by davidread** [comment]
Thanks, I've updated the readme.
