### ISSUE TITLE
Error in "Install the DGU Drupal Distribution"

### ISSUE THREAD

**Issue by gianmere** [datagovuk/dgu-vagrant-puppet#61]
Hi,

I have a problem when I try to install the DGU Drupal Distribution.

When I write the command:
drush --yes en dgu_app dgu_blog dgu_consultation dgu_data_set dgu_data_set_request dgu_footer dgu_forum dgu_glossary dgu_idea dgu_library dgu_linked_data dgu_location dgu_organogram dgu_promo_items dgu_reply dgu_shared_fields dgu_user dgu_taxonomy ckan dgu_search dgu_services dgu_home_page dgu_moderation

I have the error:
dgu_promo_items was not found
and
dgu_home_page was not found

After, when I finish the step "Drupal content", and I try to load the page " http://192.168.11.11/user"
I have the error:
"The website encountered an unexpected error. Please try again later."

How can I resolt this ?

Thanks

**Comment by davidread** [comment]
@ratajczak do you know about this?

**Comment by ratajczak** [comment]
I know that dgu_promo_items and dgu_home_page are features which has been removed from the repository long time ago.
@gianmere why are you executing this command?

TBH I'm not familiar with this repository but I believe it's obsolete (last commit was 14 months ago). I think the development has moved here:
https://github.com/datagovuk/linux_puppet

You can type "drush vset -y error_level 2" in Drupal root folder to display full error reports instead "The website encountered an unexpected error. Please try again later.".

**Comment by gianmere** [comment]
I want to install a copy of data.gov.uk's website to my own server and customize it.
I am following these instructions https://github.com/datagovuk/dgu-vagrant-puppet/blob/togo/README.md.

Am I wrong ?

**Comment by davidread** [comment]
@gianmere yes you are following the correct instructions.

@ratajczak you need to look at the 'togo' branch to see everything.

@gianmere have you tried setting the error_level like @pawel suggests?

**Comment by ratajczak** [comment]
@gianmere I've updated Drupal installation instructions here: https://github.com/datagovuk/dgu-vagrant-puppet/blob/togo/README.md. 

This is updated command:

drush --yes en dgu_app dgu_blog dgu_consultation dgu_data_set dgu_data_set_request dgu_footer dgu_forum dgu_glossary dgu_idea dgu_library dgu_linked_data dgu_location dgu_moderation dgu_notifications dgu_organogram dgu_print dgu_reply dgu_search dgu_services dgu_user ckan 

Could you please try again?

**Comment by davidread** [comment]
@ratajczak has fixed the drush command to avoid the warnings:

https://github.com/datagovuk/dgu-vagrant-puppet/commit/8bf0923e80401239d309cabc6d25d3ecb404cb3d

**Comment by davidread** [comment]
@ratajczak I reproduced what @gianmere saw. I changed the debug level and got some warnings:
```
(ckan)co@precise64:/var/www/drupal/dgu$ drush vset -y error_level 2
class_implements(): Class RedirectController does not exist and[warning]
could not be loaded entity.module:508
in_array() expects parameter 2 to be array, boolean given      [warning]
entity.module:508
class_implements(): Class RedirectController does not exist and[warning]
could not be loaded entity.module:72
in_array() expects parameter 2 to be array, boolean given      [warning]
entity.module:72
error_level was set to "2".                                    [success]
```
And when I view the homepage it shows this error:
```
 PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause': SELECT redirect.rid AS rid FROM {redirect} redirect WHERE (status = :db_condition_placeholder_0) AND (source LIKE :db_condition_placeholder_1 ESCAPE '\\') AND (language IN (:db_condition_placeholder_2, :db_condition_placeholder_3)) ; Array ( [:db_condition_placeholder_0] => 1 [:db_condition_placeholder_1] => user [:db_condition_placeholder_2] => en [:db_condition_placeholder_3] => und ) in redirect_load_by_source() (line 584 of /var/www/drupal/dgu/profiles/dgu/modules/contrib/redirect/redirect.module).
```

**Comment by ratajczak** [comment]
@davidread have you used sample database? I believe that this sample database is not up to date, could you please execute "drush updb" in Drupal root folder and let me know if this message is gone?

**Comment by davidread** [comment]
Yes that fixes it for me. @gianmere do you want to give that a go?

@ratajczak are you able to get the sample database updated?

**Comment by ratajczak** [comment]
@davidread yes, I'll update it and post here when it's done.

**Comment by ratajczak** [comment]
@gianmere I just updated our sample database, you shouldn't get any errors now

**Comment by davidread** [comment]
Cheers @ratajczak

**Comment by gianmere** [comment]
It works without errors !!!
You are great.

Thanks
