### ISSUE TITLE
Error with the "http://localhost/data/search"

### ISSUE THREAD

**Issue by bb-mm** [datagovuk/dgu-vagrant-puppet#62]
Hi,

I followed all the instructions on README(to go) and successfully set up a copy of data.gov.uk's website on my own server. But when I tried with the "http://localhost/data/search" or clicked "Datasets" tab on the website, I got this:

![image](https://cloud.githubusercontent.com/assets/4938563/5896612/69c71844-a573-11e4-9478-211823601600.png)

I followed the instructions on CKAN Database setup and use the `create-test-data` command. No error happened. And the logs in `/var/log/ckan/ckan-apache.error.log` was the same with that on README.

**Comment by davidread** [comment]
Ah, since a couple of days ago you need to change this in your ckan.ini:

    ckan.legacy_templates = false

I've fixed this in the template now:
https://github.com/datagovuk/dgu-vagrant-puppet/commit/3ab2f104fc05b0480af4fb28ab3f64028a4b1c88#diff-d71b0cb7a422391b640b46b214a54c5aL51
