### ISSUE TITLE
Broken links report not working

### ISSUE THREAD

**Issue by tbalaz** [datagovuk/dgu-vagrant-puppet#68]
Hi,

/data/report/broken-links shows no broken links although they exists.

Is there some job that crawls trough site to check for errors?

What can we check to resolve this issue?

Thank you.

**Comment by davidread** [comment]
This is done by the Archiver. The set-up should be covered by the new bit in the docs:

https://github.com/datagovuk/dgu-vagrant-puppet/commit/b682bf26de37530b860491110d611a33477c0fef
