### ISSUE TITLE
Enabling resource caching

### ISSUE THREAD

**Issue by tbalaz** [datagovuk/dgu-vagrant-puppet#71]
Hi,

how can we enable caching?

![image](https://cloud.githubusercontent.com/assets/8652002/6081244/6a6106d6-ae18-11e4-949a-ba224340b9a8.png)

We have no available cache message.

![image](https://cloud.githubusercontent.com/assets/8652002/6081321/f4c19782-ae18-11e4-8f2a-e397c748b266.png)

Thank you.

**Comment by davidread** [comment]
I've added some instructions for this now:

https://github.com/datagovuk/dgu-vagrant-puppet/commit/b682bf26de37530b860491110d611a33477c0fef

Let me know how you get on.

**Comment by tbalaz** [comment]
Ok, caching works now.

Thank you.

**Comment by davidread** [comment]
Great to hear it, thanks
