### ISSUE TITLE
Setting up Quality Check and Resource Openness

### ISSUE THREAD

**Issue by tbalaz** [datagovuk/dgu-vagrant-puppet#72]
We would like to setup Quality Check like on data.gov.uk site.

![image](https://cloud.githubusercontent.com/assets/8652002/6081381/48036560-ae19-11e4-827d-f982c296ed09.png)

Where we can enable this feature and is it connected with Resource Openness rating?

We can't find how to rate resource openness.

Thank you.

**Comment by davidread** [comment]
This is done by the QA. The set-up should be covered by the new bit in the docs:

https://github.com/datagovuk/dgu-vagrant-puppet/commit/b682bf26de37530b860491110d611a33477c0fef
