### ISSUE TITLE
Encoding themes

### ISSUE THREAD

**Issue by markoOmega** [datagovuk/dgu-vagrant-puppet#73]
The problem is with croatian words like ć,č,š etc.
When I change theme names in json themes it is all ok until i choose dataset then it breaks.
Error:
⇝ UnicodeEncodeError: 'ascii' codec can't encode character u'\u0161' in position 5: ordinal not in range(128)
View as:   Interactive (full)  |  Text (full)  |  XML (full)
Module ?:120 in <Expression u'iter(h.get_package_fields(c.pkg, dict(c.pkg_extras),h.dataset_type(c.pkg_extras)))'>          view
>>  <tr py:for="field_dict, label_attributes, value_attributes in h.get_package_fields(c.pkg, dict(c.pkg_extras),h.dataset_type(c.pkg_extras))">
Module ckanext.dgu.lib.helpers:762 in get_package_fields          view
>>  secondary_themes = str(secondary_themes)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0161' in position 5: ordinal not in range(128)

I would appreciate help

![themes](https://cloud.githubusercontent.com/assets/10724429/6081938/6cfb7d68-ae1d-11e4-816a-41f340dd02d3.PNG)
![okolis](https://cloud.githubusercontent.com/assets/10724429/6081942/72c3563a-ae1d-11e4-8b4e-34efb112ef71.PNG)

**Comment by davidread** [comment]
I believe this change should fix it:
https://github.com/datagovuk/ckanext-dgu/commit/3ab5ad46080b6a07d5f44bd39d3cc71fa6bba103
