### ISSUE TITLE
How to change app details page

### ISSUE THREAD

**Issue by VladimirZD** [datagovuk/dgu-vagrant-puppet#74]
Hi, i would like to make changes to app details page (like this one: http://data.gov.uk/apps/scope-nights-astronomy-weather-reports)

I would like to remove disclaimer but i am not sure how, i checked node template but nothing there..

Thnx

**Comment by davidread** [comment]
@ratajczak can you answer?

**Comment by noels** [comment]
The disclaimer is in the template.  profiles/dgu/themes/custom/dguk/templates/node--app.tpl.php

**Comment by VladimirZD** [comment]
Ok. We fixed disclamer.. Thnx
