### ISSUE TITLE
Problems with customization of views/nodes

### ISSUE THREAD

**Issue by VladimirZD** [datagovuk/dgu-vagrant-puppet#78]
I would like to customize data-request/ forms, but am not able to do that via drupal.
First i would like to remove some fileds (language..) from this screen /node/add/dataset-request
and then to change message "Your Dataset Request has been created and submitted for moderation...."

Is it  possible to do that via drupal or i have to change code?

thnx

**Comment by davidread** [comment]
@ratajczak any hints?

**Comment by VladimirZD** [comment]
We have solved this one... For drupal tempaltes it is easy if they are not using t(string) function then change code to use it and translate it in drupal translation interface, or change translation in source...
