### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by VladimirZD** [datagovuk/dgu-vagrant-puppet#80]
When i go to page /admin/content/ckan_datasets i can see only 5 datasets..

![image](https://cloud.githubusercontent.com/assets/8065995/6205513/b419c36c-b570-11e4-8d05-fe0bcb9f8c38.png)

When i go to /data/search  i have 72 datasets there...
Datasets from /admin/content/ckan_datasets are used on app submiting so there we can see only 5 of them.. in field uses dataset and we have 72 at moment..

I know that 72 datasets i see are in CKAN and this 5 are in drupal and i need some kind o sync...
It seems we are missing some  job or script, any hints?

Thank you

**Comment by davidread** [comment]
I think you need the section in the readme called "Syncing publishers and datasets from CKAN to Drupal"

**Comment by VladimirZD** [comment]
Thnx. We will check it out...

**Comment by VladimirZD** [comment]
Everything i working fine. Thnx for help
