### ISSUE TITLE
Problems with localization

### ISSUE THREAD

**Issue by VladimirZD** [datagovuk/dgu-vagrant-puppet#83]
Hi i can't localize /data-request/"request_name"
![image](https://cloud.githubusercontent.com/assets/8065995/6227785/5e327e64-b6a4-11e4-807d-a6628fba5fe3.png)

I have problem with fields, i see them in translation interface enter new value, but in form i still see old ones...

Only way which is working is to change values in field definiton (admin/structure/types/manage/dataset-request/fields/field_organisation_type/field-settings). But this isn't localization...

Any hints?

Thnx

**Comment by davidread** [comment]
I assume this is standard drupal localization. This isn't something we do in DGU, so if wouldn't mind, please refer to Drupal docs/community.
