### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by tbalaz** [datagovuk/dgu-vagrant-puppet#85]
Running 

/home/co/ckan/bin/paster --plugin=ckan celeryd run concurrency=1 --queue=priority --config=/var/ckan/ckan.ini

in supervisord, breaks /data/search site (Getting Server Error 500)

This is the error in error.log:

Please specify a ckan.storage_path in your config for your uploads.

i have defined ckan.storage_path in ckan.ini.

After stopping program in supervisord. Site goes back up. This does not happen every time i start job but occasionally. Haven't figured out pattern yet.

Does anyone have suggestions where to look for cause.

Thank You,

**Comment by davidread** [comment]
You didn't run paster as user 'www-data'. So I suspect you fell foul of this issue: https://github.com/datagovuk/dgu-vagrant-puppet/tree/togo#log-permissions

The eror about storage_path is a red herring - ignore it. Is there another error in /var/log/ckan/ckan-apache.error.log ?

**Comment by tbalaz** [comment]
Running paster as user 'www-data' solves the problem.

Thank you,
