### ISSUE TITLE
Caching does not work

### ISSUE THREAD

**Issue by tbalaz** [datagovuk/dgu-vagrant-puppet#86]
Hi,

after setting up QA, Archiver and  Harvesting as explained in 

https://github.com/datagovuk/dgu-vagrant-puppet/commit/b682bf26de37530b860491110d611a33477c0fef

I have no cached files.

all jobs are running under supervisor

![supervisord](https://cloud.githubusercontent.com/assets/8652002/6287464/f95b29bc-b911-11e4-9002-c9ae6f8a7b19.PNG)

and i have added cron jobs like explained in instructions.

![cron](https://cloud.githubusercontent.com/assets/8652002/6287562/cd579ac0-b912-11e4-980d-d7830d6984ea.PNG)

There are no errors in supervisord program log or syslog.

Please advice.

**Comment by davidread** [comment]
I'm not sure sudo would work in cron. I think it would be better to use the system wide cron /etc/ckan/cron.d

When you run this on the command-line:

    sudo -u www-data /home/co/ckan/bin/paster --plugin=ckanext-archiver archiver update --config=/var/ckan/ckan.ini

can you provide the output of the command-line and celery log please? This will try and do all your datasets, so you might add the name of a single dataset of yours as a parameter to just do that one.

**Comment by tbalaz** [comment]
Hi David,

file caching started after changing celeryd --queue from priority to bulk.

i'm still having problem with cached file URL. URL is showing http://localhost:5000 instead http://data.gov.hr:5000.

Is this URL defined by ckan.cache_url_root in ckan.ini or by something else?

Thank you.

**Comment by davidread** [comment]
Ah, my mistake - sorry. I've fixed the --queue in the docs now.

And yes, ckan.cache_url_root is the one to change. You'll need to do another 'archiver update' to store the new URLs for the cached resources.

https://github.com/datagovuk/dgu-vagrant-puppet/commit/e526cbced7dd1e20911c98f61ff72a8abca7a600

**Comment by tbalaz** [comment]
Thank you David,

caching works after changing ckan.ini
