### ISSUE TITLE
Missing elements in miscellaneous

### ISSUE THREAD

**Issue by tbalaz** [datagovuk/dgu-vagrant-puppet#88]
Hi,

i'm missing some elements in miscellaneous tab of Drupal.

This is screenshot of default deployment of dgu-vagrant-puppet togo branch.

![togo](https://cloud.githubusercontent.com/assets/8652002/6459383/661159ee-c18e-11e4-8aff-3c6c7bf37cb7.png)

And this is what i have

![datagovhr](https://cloud.githubusercontent.com/assets/8652002/6459397/7dae4328-c18e-11e4-89f8-9485e6fbfcd9.png)

I would like to add **Data requests by outcome** and **Data requests by status** but i don't have those options.

Please advice,

**Comment by davidread** [comment]
Could you explain how your setup differs from the DGUToGo one? And perhaps @ratajczak can comment.

**Comment by VladimirZD** [comment]
David, we are not sure, we made a bunch of changes (mainly localization...) , and  disabled few modules.. For start i would like to know where should components listed in  miscellaneous  be located, so i can check if they are instaled ?

Thank you

**Comment by VladimirZD** [comment]
We have installed new instance from togo package and all elements are there, i think we turned some modules off , i will look into it later. @tbalaz  please close this one..

**Comment by ratajczak** [comment]
@tbalaz these are ctools plugins. Could you please confirm that you have these files in your code base of your Drupal instance:
https://github.com/datagovuk/dgu_d7/blob/master/modules/features/dgu_data_set_request/plugins/content_types/dgu_data_set_request_status.inc
https://github.com/datagovuk/dgu_d7/blob/master/modules/features/dgu_data_set_request/plugins/content_types/dgu_data_set_request_outcome.inc

**Comment by VladimirZD** [comment]
Hi
@ratajczak  , we are trying to sort this out. First problem was that in our instalation files there was no plugins folder, it seems that module data_set_request was updated after we cloned files (it as about 10/2014)  
We got new modules yesterday and updated folders now we have some problems with D3 but @tbalaz  is sorting that out.. If we get stuck we will let you know.

**Comment by davidread** [comment]
No further questions, closing for now.
