### ISSUE TITLE
Dataset-request-error

### ISSUE THREAD

**Issue by markoOmega** [datagovuk/dgu-vagrant-puppet#90]
When I'm in edit draft mode with dataset-request and click on send for review it redirect me to error page. In pictures are details of error.
![error](https://cloud.githubusercontent.com/assets/10724429/6504310/09f5599a-c336-11e4-92a6-4ab5e334d6b7.PNG)
![head](https://cloud.githubusercontent.com/assets/10724429/6504311/09f6ad68-c336-11e4-9d06-af0b96223d8d.PNG)

**Comment by VladimirZD** [comment]
Hi, we installed new instance from togo branch without any modifications and we get same error...
IT is at moment pretty big issue... Does any1 has any idea?

Thnx

**Comment by davidread** [comment]
@ratajczak do you know why this might happen?

**Comment by ratajczak** [comment]
Can you confirm that you are getting this error?
Fatal error: Call to undefined function message_subscribe_flag_get_flags() /profiles/dgu/modules/features/dgu_data_set_request/dgu_data_set_request.module on line 509

**Comment by markoOmega** [comment]
Yes that is solution. Thank you very much for help.
