### ISSUE TITLE
Unauthorized to create a package?

### ISSUE THREAD

**Issue by goozi** [datagovuk/dgu-vagrant-puppet#91]
Hi!
When I "Add a Dataset" , the site prompt "Unauthorized to create a package".

I'm logged on to site with user that have this roles:
 administrator
 blogger
 ckan adminstrator
 data publisher
 data request administrator
 glossary moderator
 moderator
 news editor

Please advice!

**Comment by VladimirZD** [comment]
Is user you are assigned added to any publisher?

**Comment by goozi** [comment]
Yes, I have been added to the publishers in the sample.

**Comment by tbalaz** [comment]
What is written to ckan.log when you try to add dataset.

**Comment by goozi** [comment]
【ckan-apache.error.log 】
[Wed Mar 11 10:07:00 2015] [error] 2015-03-11 10:07:00,215 DEBUG [ckanext.dgu.authentication.drupal_auth] Drupal cookie
 found for server request 123.57.64.21
[Wed Mar 11 10:07:00 2015] [error] 2015-03-11 10:07:00,216 INFO  [ckanext.dgu.drupalclient] XMLRPC connection to http:/
/ckan:lxxxxxx@localhost:80/services/xmlrpc
[Wed Mar 11 10:07:00 2015] [error] 2015-03-11 10:07:00,472 INFO  [ckanext.dgu.drupalclient] Obtained Drupal user_id for
 session ID '3B9j'...: '451357'
[Wed Mar 11 10:07:00 2015] [error] 2015-03-11 10:07:00,732 INFO  [ckanext.dgu.drupalclient] Obtained Drupal user: u"{'r
df_mapping': {'homepage': {'predicates': ['foaf:page'], 'type': 'rel'}, 'name': {'predicates': ['foaf:name']}, 'rdftype
': ['sioc:UserAccount']}, 'uid': '451357', 'timezone': 'Asia/Shanghai', 'field"
[Wed Mar 11 10:07:00 2015] [error] 2015-03-11 10:07:00,751 DEBUG [ckanext.dgu.authentication.drupal_auth] Drupal user f
ound in CKAN: user_d451357
[Wed Mar 11 10:07:00 2015] [error] 2015-03-11 10:07:00,752 DEBUG [ckanext.dgu.authentication.drupal_auth] User roles in
 Drupal: ['editor', 'news editor', 'data request administrator', 'administrator', 'authenticated user', 'ckan adminstra
tor', 'glossary moderator', 'moderator', 'data publisher', 'blogger']
[Wed Mar 11 10:07:00 2015] [error] 2015-03-11 10:07:00,753 INFO  [ckanext.dgu.authentication.drupal_auth] User made a s
ysadmin: user_d451357
[Wed Mar 11 10:07:00 2015] [error] 2015-03-11 10:07:00,753 INFO  [ckanext.dgu.authentication.auth_tkt] Remembering Drup
al identity
[Wed Mar 11 10:07:00 2015] [error] 2015-03-11 10:07:00,754 DEBUG [ckanext.dgu.authentication.drupal_auth] Set REMOTE_US
ER = u'user_d451357'

**Comment by tbalaz** [comment]
Please check this:

https://github.com/datagovuk/dgu-vagrant-puppet/issues/41

**Comment by goozi** [comment]
Hi,
I can't see list of sysadmins at http://123.57.64.21/ckan-admin, the site prompt
![2618939a-53e1-43bf-9b6d-b3b817868654](https://cloud.githubusercontent.com/assets/1628189/6614580/cbd2923a-c8d6-11e4-8734-29478bf882be.png)
Jason user is member of Drupal administrator role.

**Comment by davidread** [comment]
@goozi you need to make your user a 'sysadmin' in ckan. See the docs:
https://github.com/datagovuk/dgu-vagrant-puppet/tree/togo#give-yourself-a-ckan-user-for-debug-optional

As @tbalaz mentioned, in PR #41 we plan to inherit this role into CKAN from Drupal roles, but that hasn't been merged yet I'm afraid.

**Comment by goozi** [comment]
It's works!  Thank you so much @davidread !
And thanks to all the guys to help me !

**Comment by davidread** [comment]
Good! Thanks all for helping.

BTW I'm creating guidance that explains a bit more about using the backend of the system, mainly the CKAN parts. It might help in general, and it has some bits about becoming an Editor: http://datagovuk.github.io/guidance/
