### ISSUE TITLE
How to refresh five star result

### ISSUE THREAD

**Issue by VladimirZD** [datagovuk/dgu-vagrant-puppet#92]
Hi after setting up five star ratting (https://github.com/datagovuk/dgu-vagrant-puppet/issues/89) we run job and all datasets got five star ratting and description..., then we translated messages to Croatian, and we need to rerun five star ratting for all datasets... At moment only new datasets are processed and they get Croatian translated messages, but old ones are still in english..

How can we rate all datasets again?
Thnx for help

**Comment by davidread** [comment]
This command is what you use to retry archiving and QA of datasets:

    sudo -u www-data /home/co/ckan/bin/paster --plugin=ckanext-archiver archiver update cabinet-office --config=$CKAN_INI

or to just rerate them:

    sudo -u www-data /home/co/ckan/bin/paster --plugin=ckanext-qa qa update cabinet-office --config=$CKAN_INI

**Comment by VladimirZD** [comment]
What is cabinet office param? Is that root publisher? We don't have that kind of hierarchy, so i am wondering do we have to do it for each publisher?

I am looking at source of QQ https://github.com/datagovuk/ckanext-qa/blob/2.0/ckanext/qa/tasks.py
and i see update task has



Thank you

**Comment by davidread** [comment]
Yes, just leave off the publisher name to do all publishers. You can also do `--help` for these commands.

BTW
https://github.com/datagovuk/ckanext-qa/blob/2.0/ckanext/qa/commands.py#L27

**Comment by VladimirZD** [comment]
Ahh didn't see that...

Thank you
