### ISSUE TITLE
Server unresponsive

### ISSUE THREAD

**Issue by tbalaz** [datagovuk/dgu-vagrant-puppet#94]
@davidread 

Hi,

we have problems with apache server whenever there is ove 400 users on site.

Server becomes unresponsive.

Restarting apache server temporarily solves problem.

Can you tell me what kind of hardware you have for datagov.uk? Do you have load balancing with nginx or something?

Thanks.

**Comment by davidread** [comment]
Have you enabled caching? Most users should not be logged in, so you can serve them from the cache. We use varnish. Or you could configure nginx to do it.

**Comment by tbalaz** [comment]
@davidread 

Hi,

we haven't enabled caching yet but we have done some tweeks on apache and postgre.

Everything works fine now.

we have tested site with 1000 users load and server didn't crash.

We have changed options in prefork.conf and max connections value in postgre config.

Also we have changed WSGIDaemonProcess from singlethreaded to processes=4 threads=25 in apache ckan.conf.

When you ask "Have you enabled caching?" do you mean have we implemanted caching server or there is some caching engine in dgu-vagrant-puppet that we did not see?

**Comment by davidread** [comment]
I think the conclusion a while back was that CKAN wasn't multi-thread safe, so very occasionally you might see an issue by doing that.

I meant configuring varnish or something on top of apache, that caches HTTP requests to it and responses from it. Great to hear your load test have gone well.
